---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/integration/fixtures

platforms:
  - name: ubuntu-14.04

suites:
  - name: Integration
    run_list:
      - recipe[bazaar_test::default]
