---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/integration/fixtures

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bazaar_test::default]
      - recipe[bazaar_test::checkout]
      - recipe[bazaar_test::update]
      - recipe[bazaar_test::sync]
